# Generated by Django 5.1.7 on 2025-03-08 03:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0002_profilvoyageur_ville_adresse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Hebergement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('adresse', models.CharField(blank=True, max_length=200, null=True)),
                ('type_hebergement', models.CharField(blank=True, max_length=50, null=True)),
                ('etoiles', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_transport', models.CharField(max_length=50)),
                ('compagnie', models.CharField(blank=True, max_length=100, null=True)),
                ('confort', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeVoyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CritereVoyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_depart', models.DateField()),
                ('date_retour', models.DateField()),
                ('budget_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nombre_voyageurs', models.PositiveIntegerField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('activites_souhaitees', models.ManyToManyField(to='voyage.activite')),
                ('adresse_arrivee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adresse_arrivee_voyages', to='voyage.adresse')),
                ('adresse_depart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adresse_depart_voyages', to='voyage.adresse')),
                ('pays_arrivee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pays_arrivee_voyages', to='voyage.pays')),
                ('pays_depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pays_depart_voyages', to='voyage.pays')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ville_depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depart_voyages', to='voyage.ville')),
                ('ville_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_voyages', to='voyage.ville')),
                ('hebergement_prefere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='voyage.hebergement')),
                ('moyen_transport_prefere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='voyage.transport')),
                ('type_voyage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='voyage.typevoyage')),
            ],
        ),
    ]
