# Generated by Django 5.1.7 on 2025-03-08 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0003_activite_hebergement_transport_typevoyage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanVoyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu_plan', models.JSONField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('critere_voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voyage.criterevoyage')),
            ],
        ),
    ]
