# Generated by Django 5.1.7 on 2025-03-13 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0004_planvoyage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criterevoyage',
            name='activites_souhaitees',
        ),
        migrations.RemoveField(
            model_name='criterevoyage',
            name='hebergement_prefere',
        ),
        migrations.RemoveField(
            model_name='criterevoyage',
            name='moyen_transport_prefere',
        ),
        migrations.RemoveField(
            model_name='criterevoyage',
            name='adresse_arrivee',
        ),
        migrations.RemoveField(
            model_name='criterevoyage',
            name='nombre_voyageurs',
        ),
        migrations.RemoveField(
            model_name='criterevoyage',
            name='pays_depart',
        ),
        migrations.RemoveField(
            model_name='criterevoyage',
            name='ville_depart',
        ),
        migrations.DeleteModel(
            name='Activite',
        ),
        migrations.DeleteModel(
            name='Hebergement',
        ),
        migrations.DeleteModel(
            name='Transport',
        ),
    ]
