# Generated by Django 5.1.7 on 2025-03-14 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0005_remove_criterevoyage_activites_souhaitees_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilvoyageur',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profilvoyageur',
            name='pays_favoris',
        ),
        migrations.RemoveField(
            model_name='criterevoyage',
            name='pays_arrivee',
        ),
        migrations.AlterField(
            model_name='criterevoyage',
            name='type_voyage',
            field=models.CharField(choices=[('loisir', 'Loisir'), ('affaires', 'Affaires'), ('familial', 'Familial'), ('culturel', 'Culturel'), ('aventure', 'Aventure'), ('romantique', 'Romantique'), ('religieux', 'Religieux'), ('etudes', 'Études'), ('autre', 'Autre')], default='autre', max_length=20),
        ),
        migrations.RemoveField(
            model_name='criterevoyage',
            name='ville_destination',
        ),
        migrations.CreateModel(
            name='TrancheAgeVoyageur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tranche_age', models.CharField(choices=[('enfant', 'Enfant (0-12 ans)'), ('jeune', 'Jeune (13-25 ans)'), ('adulte', 'Adulte (26-60 ans)'), ('senior', 'Senior (+60 ans)')], max_length=20)),
                ('nombre_voyageurs', models.PositiveIntegerField(default=1)),
                ('critere_voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tranches_age_voyageurs', to='voyage.criterevoyage')),
            ],
        ),
        migrations.AddField(
            model_name='criterevoyage',
            name='pays_arrivee',
            field=models.ManyToManyField(related_name='pays_arrivee_voyages', to='voyage.pays'),
        ),
        migrations.AddField(
            model_name='criterevoyage',
            name='ville_destination',
            field=models.ManyToManyField(related_name='destination_voyages', to='voyage.ville'),
        ),
    ]
