# Generated by Django 5.1.7 on 2025-03-20 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0008_itineraire_deplacement_activite_voyage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfilVoyageur',
            new_name='Voyageur',
        ),
        migrations.RemoveField(
            model_name='itineraire',
            name='voyage',
        ),
        migrations.RemoveField(
            model_name='activite',
            name='itineraire',
        ),
        migrations.RemoveField(
            model_name='voyage',
            name='critere',
        ),
        migrations.AddField(
            model_name='activite',
            name='prix',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='criterevoyage',
            name='type_voyage',
            field=models.CharField(choices=[('loisir', 'Loisir'), ('affaires', 'Affaires'), ('familial', 'Familial'), ('culturel', 'Culturel'), ('aventure', 'Aventure'), ('romantique', 'Romantique'), ('religieux', 'Religieux')], max_length=20),
        ),
        migrations.CreateModel(
            name='JourVoyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.IntegerField()),
                ('date', models.DateField()),
                ('critere_voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jour', to='voyage.criterevoyage')),
            ],
        ),
        migrations.AddField(
            model_name='activite',
            name='jour_voyage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activites', to='voyage.jourvoyage'),
        ),
        migrations.DeleteModel(
            name='Deplacement',
        ),
        migrations.DeleteModel(
            name='Itineraire',
        ),
        migrations.DeleteModel(
            name='Voyage',
        ),
    ]
