# Generated by Django 5.1.7 on 2025-04-17 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0009_rename_profilvoyageur_voyageur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='criterevoyage',
            name='adresse',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='criterevoyage',
            name='voyageurs_adulte',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='criterevoyage',
            name='voyageurs_enfant',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='criterevoyage',
            name='voyageurs_jeune',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='criterevoyage',
            name='voyageurs_senior',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='criterevoyage',
            name='type_voyage',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
