# Generated by Django 5.1.7 on 2025-05-22 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0010_criterevoyage_adresse_criterevoyage_voyageurs_adulte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='criterevoyage',
            name='api_choisie',
            field=models.CharField(choices=[('deepseek', 'DeepSeek'), ('openai', 'OpenAI')], default='deepseek', max_length=20),
        ),
    ]
