# Generated by Django 5.1.7 on 2025-05-23 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0011_criterevoyage_api_choisie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criterevoyage',
            name='adresse_depart',
        ),
    ]
